<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.6">
  <POU Name="FB_Qa" Id="{f0715c0c-30b0-4295-ae4b-91cb1e50682c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Qa
VAR_INPUT
	///consigne dans l'unité de l'utilisateur, selon min et max de fbCongig.stValeur
	lrConsigne: LREAL;
	///configuration de la sortie analogique
	fbConfig: FB_ConfigAnalog;
END_VAR
VAR_OUTPUT
	///sortie analogique, atention, supprimer MatchingSize lors de la liaison avec la borne
	QaSortie AT %Q*: DINT;
	///écart de précision sur la valeur de consigne => valeur +/- écart
	lrEcart: LREAL;
	///tension en volt
	lrTension: LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// 
QaSortie:=fbConfig.mConvertValToAn(lrConsigne,lrTension=>lrTension,lrEcart=>lrEcart);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>